/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: specter (https://sketchfab.com/specter)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/739af7000c0242d8b327d7fdf6062aaa
title: drifting Astronaut
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../scene.gltf')
  const ROTATION_SPEED = 0.00009;
  
  useFrame(()=>{
    if (group.current.rotation.x < 0) {
      group.current.rotation.x = group.current.rotation.x += ROTATION_SPEED;
    } 
    if ( group.current.rotation.y < 0) {
      group.current.rotation.y = group.current.rotation.y += ROTATION_SPEED;
    }
    if ( group.current.rotation.z < 0) {
      group.current.rotation.z = group.current.rotation.z += ROTATION_SPEED;
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 122.36, -19.04]}>
            <mesh geometry={nodes.Backpack_Mat_0.geometry} material={materials.material} />
          </group>
          <group position={[371.75, 94.89, -151.82]} rotation={[-0.38, 0, 0]}>
            <mesh geometry={nodes.Rope_tip_Chrome_0.geometry} material={materials.Chrome} />
          </group>
          <mesh geometry={nodes.Rope_Mat_0.geometry} material={materials.Mat_0} />
          <mesh geometry={nodes.Rope_Mat1_1.geometry} material={materials['Mat.1']} />
          <mesh geometry={nodes.Rope_Mat2_2.geometry} material={materials['Mat.2']} />
          <group position={[0.07, 56.13, 3.47]}>
            <group position={[-0.07, -56.13, -3.47]}>
              <group position={[0, 164.43, 12.6]}>
                <mesh geometry={nodes.Helmet_1_Mat_1.geometry} material={materials.Mat_1} />
                <mesh geometry={nodes.Helmet_1_Glass_1.geometry} material={nodes.Helmet_1_Glass_1.material} />
                <mesh geometry={nodes.Helmet_1_Mat1_0.geometry} material={materials['Mat.1_0']} />
              </group>
              <group position={[0, 164.43, 12.6]}>
                <mesh geometry={nodes.GLASS_Glass_0.geometry} material={nodes.GLASS_Glass_0.material} />
              </group>
            </group>
            <group position={[0.35, 100.78, -2.84]} rotation={[0.71, 0.04, 0.21]}>
              <mesh geometry={nodes.Skull_Bone_0.geometry} material={materials.Bone} />
            </group>
            <group position={[-0.07, -56.13, -3.47]}>
              <mesh geometry={nodes.Astronaut_Body_2_Mat_0.geometry} material={materials.Mat_2} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../scene.gltf')
